name: sign_learn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1

  intl: ^0.20.2

  flutter_svg: ^2.0.17

  # Firebase Dependencies
  firebase_core: ^3.12.0
  firebase_auth:
  firebase_storage:
  cloud_firestore:

  # Memory Dependencies
  shared_preferences: ^2.5.2

  # StateManagment Dependencies
  riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1

  #
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  auto_route: ^10.0.1

  dio: ^5.8.0+1

  # Video player Dependencies
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.4.1

  # 
  connectivity_plus: ^6.1.4
  data_connection_checker_tv: ^0.3.5-nullsafety
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^2.5.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/home_icons/
    - assets/Icons/misc_icons/
    - assets/Icons/social_icons/
    - assets/Icons/profile_icons/

  fonts:
    - family: Clash display
      fonts:
        - asset: assets/fonts/clash_display/ClashDisplay-Bold.otf
          weight: 700

        - asset: assets/fonts/clash_display/ClashDisplay-Semibold.otf
          weight: 600

        - asset: assets/fonts/clash_display/ClashDisplay-Medium.otf
          weight: 500

        - asset: assets/fonts/clash_display/ClashDisplay-Regular.otf
          weight: 400

        - asset: assets/fonts/clash_display/ClashDisplay-Light.otf
          weight: 300

        - asset: assets/fonts/clash_display/ClashDisplay-Extralight.otf
          weight: 200

    - family: General Sans
      fonts:
        - asset: assets/fonts/general_sans/GeneralSans-Bold.otf
          weight: 700

        - asset: assets/fonts/general_sans/GeneralSans-Semibold.otf
          weight: 600

        - asset: assets/fonts/general_sans/GeneralSans-Medium.otf
          weight: 500

        - asset: assets/fonts/general_sans/GeneralSans-Regular.otf
          weight: 400

        - asset: assets/fonts/general_sans/GeneralSans-Light.otf
          weight: 300

        - asset: assets/fonts/general_sans/GeneralSans-Extralight.otf
          weight: 200

    - family: Athletics
      fonts:
        - asset: assets/fonts/athletics/Athletics-Black.otf
          weight: 900

        - asset: assets/fonts/athletics/Athletics-ExtraBold.otf
          weight: 800

        - asset: assets/fonts/athletics/Athletics-Bold.otf
          weight: 700

        - asset: assets/fonts/athletics/Athletics-Medium.otf
          weight: 500

        - asset: assets/fonts/athletics/Athletics-Regular.otf
          weight: 400

        - asset: assets/fonts/athletics/Athletics-Light.otf
          weight: 300

    - family: SF Rounded
      fonts:
        - asset: assets/fonts/sf/SF-Pro-Rounded-Black.otf
          weight: 900

        - asset: assets/fonts/sf/SF-Pro-Rounded-Heavy.otf
          weight: 800

        - asset: assets/fonts/sf/SF-Pro-Rounded-Bold.otf
          weight: 700

        - asset: assets/fonts/sf/SF-Pro-Rounded-SemiBold.otf
          weight: 600

        - asset: assets/fonts/sf/SF-Pro-Rounded-Medium.otf
          weight: 500

        - asset: assets/fonts/sf/SF-Pro-Rounded-Regular.otf
          weight: 400

        - asset: assets/fonts/sf/SF-Pro-Rounded-Light.otf
          weight: 300

        - asset: assets/fonts/sf/SF-Pro-Rounded-Ultralight.otf
          weight: 200

        - asset: assets/fonts/sf/SF-Pro-Rounded-Thin.otf
          weight: 100

    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
          weight: 900

        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
          weight: 900
          style: italic

        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700

        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500

        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400

        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 300

        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
          weight: 300
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
